# Generated by Django 3.1.3 on 2020-12-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandhills_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone_contact', models.CharField(max_length=15)),
                ('email_add', models.EmailField(max_length=254)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='siteinfor',
            old_name='title',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='siteinfor',
            name='company_addi_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteinfor',
            name='company_definition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteinfor',
            name='company_vision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteinfor',
            name='email_add_one',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siteinfor',
            name='email_add_two',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='siteinfor',
            name='phone_contact_one',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='siteinfor',
            name='phone_contact_two',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
