# Generated by Django 3.1.3 on 2020-12-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandhills_site', '0002_auto_20201227_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfor',
            name='company_definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfor',
            name='company_vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
