# Generated by Django 3.1.4 on 2021-01-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grandhills_site', '0004_auto_20201229_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfor',
            name='email_add_two',
        ),
    ]
